services:     
  kafka:
    image: apache/kafka:3.9.0-rc2
    container_name: kafka
    restart: unless-stopped
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: 
        BROKER://kafka:9092,
        CONTROLLER://kafka:9093,
        INTERNAL://kafka:29092
      KAFKA_ADVERTISED_LISTENERS:
        BROKER://kafka:9092,
        INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT, CONTROLLER:PLAINTEXT, INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "nc -zv kafka 9092"]
      start_period: 1m
      interval: 1m
      timeout: 30s
      retries: 3
  
  publisher-service-db:
    image: postgres:17
    container_name: publisher-service-db
    depends_on:
      kafka:
        condition: service_healthy
    hostname: publisher-service-db
    restart: unless-stopped
    ports:
      - 5432:5432
    user: postgres
    environment:
      POSTGRES_DB: distcomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_AUTH_METHOD: TRUST
    volumes:
      - publisher-service-db-data:/var/lib/postgresql/17/main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --quiet"]
      start_period: 1m
      interval: 1m
      timeout: 30s
      retries: 3
  
  publisher-service:
    image: publisher-service:0.0.1-SNAPSHOT
    container_name: publisher-service
    restart: unless-stopped
    ports:
      - "24110:24110"
    depends_on:
      publisher-service-db:
        condition: service_healthy
    build:
      context: ./publisher-service
      dockerfile: Dockerfile
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://publisher-service-db:5432/distcomp
    healthcheck:
      test: ["CMD-SHELL", "nc -zv publisher-service 24110"]
      start_period: 1m
      interval: 1m
      timeout: 30s
      retries: 3
      
  discussion-service-db:
    image: cassandra:5.0.1
    container_name: discussion-service-db
    depends_on:
      publisher-service:
        condition: service_healthy
    restart: unless-stopped
    hostname: discussion-service-db
    ports:
      - 9042:9042
    user: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: 'Distcomp Cluster'
      CASSANDRA_KEYSPACE_NAME: distcomp
      CASSANDRA_DC: datacenter1
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    volumes:
      - discussion-service-db-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESC KEYSPACES'"]
      start_period: 2m
      interval: 1m
      timeout: 30s
      retries: 3
 
  discussion-service-create-keyspace:
    image: cassandra:5.0.1
    container_name: discussion-service-create-keyspace
    depends_on:
      discussion-service-db:
        condition: service_healthy
    volumes:
      - ./discussion-service/infrastructure/db/create_keyspace.cql:/docker-entrypoint-initdb.d/create_keyspace.cql
    command: /bin/bash -c "echo Creating distcomp keyspace && cqlsh discussion-service-db -f /docker-entrypoint-initdb.d/create_keyspace.cql"
  
  discussion-service:
    image: discussion-service:0.0.1-SNAPSHOT
    container_name: discussion-service
    restart: unless-stopped
    hostname: discussion-service
    ports:
      - "24130:24130"
    depends_on:
      discussion-service-create-keyspace:
        condition: service_started
    build:
      context: ./discussion-service
      dockerfile: Dockerfile
    environment:
      SPRING_CASSANDRA_KEYSPACE_NAME: distcomp
      SPRING_CASSANDRA_PORT: 9042
      SPRING_CASSANDRA_CONTACT_POINTS: discussion-service-db
      SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
      SPRING_DATASOURCE_URL: jdbc:cassandra://discussion-service-db:9042/distcomp?localdatacenter=datacenter1
      SPRING_LIQUIBASE_URL: jdbc:cassandra://discussion-service-db:9042/distcomp?localdatacenter=datacenter1&compliancemode=Liquibase
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      
volumes:
  publisher-service-db-data:
  discussion-service-db-data:
  kafka-data:
